// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.GrowingObjectNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class SubscribePartNotification2
	{
		private Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo2 _request;
		public Energistics.Etp.v12.Datatypes.Object.SubscriptionInfo2 Request
		{
			get
			{
				return this._request;
			}
			set
			{
				this._request = value;
			}
		}
	}
}
