// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class ArrayOfFloat
	{
		private List<System.Single> _values;
		public List<System.Single> Values
		{
			get
			{
				return this._values;
			}
			set
			{
				this._values = value;
			}
		}
	}
}
