// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class Contact
	{
		private string _organizationName;
		private string _contactName;
		private string _contactPhone;
		private string _contactEmail;
		public string OrganizationName
		{
			get
			{
				return this._organizationName;
			}
			set
			{
				this._organizationName = value;
			}
		}
		public string ContactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				this._contactName = value;
			}
		}
		public string ContactPhone
		{
			get
			{
				return this._contactPhone;
			}
			set
			{
				this._contactPhone = value;
			}
		}
		public string ContactEmail
		{
			get
			{
				return this._contactEmail;
			}
			set
			{
				this._contactEmail = value;
			}
		}
	}
}
