// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class DataAttribute
	{
		private int _attributeId;
		private Energistics.Etp.v12.Datatypes.DataValue _attributeValue;
		public int AttributeId
		{
			get
			{
				return this._attributeId;
			}
			set
			{
				this._attributeId = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.DataValue AttributeValue
		{
			get
			{
				return this._attributeValue;
			}
			set
			{
				this._attributeValue = value;
			}
		}
	}
}
