// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class ersatzContentType
	{
		private string _format;
		private string _family;
		private Energistics.Etp.v12.Datatypes.Version _familyVersion;
		private string _objectType;
		public string Format
		{
			get
			{
				return this._format;
			}
			set
			{
				this._format = value;
			}
		}
		public string Family
		{
			get
			{
				return this._family;
			}
			set
			{
				this._family = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Version FamilyVersion
		{
			get
			{
				return this._familyVersion;
			}
			set
			{
				this._familyVersion = value;
			}
		}
		public string ObjectType
		{
			get
			{
				return this._objectType;
			}
			set
			{
				this._objectType = value;
			}
		}
	}
}
