// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class ersatzUri
	{
		private Energistics.Etp.v12.Datatypes.ArrayOfString _dataspace;
		private Energistics.Etp.v12.Datatypes.ersatzContentType _contentType;
		private Energistics.Etp.v12.Datatypes.Uuid _uuid;
		private string _objectVersion;
		private string _queryString;
		[Microsoft.Hadoop.Avro.AvroUnion(typeof(Microsoft.Hadoop.Avro.AvroNull), typeof(ArrayOfString))]
		public Energistics.Etp.v12.Datatypes.ArrayOfString Dataspace
		{
			get
			{
				return this._dataspace;
			}
			set
			{
				this._dataspace = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.ersatzContentType ContentType
		{
			get
			{
				return this._contentType;
			}
			set
			{
				this._contentType = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Uuid Uuid
		{
			get
			{
				return this._uuid;
			}
			set
			{
				this._uuid = value;
			}
		}
		public string ObjectVersion
		{
			get
			{
				return this._objectVersion;
			}
			set
			{
				this._objectVersion = value;
			}
		}
		public string QueryString
		{
			get
			{
				return this._queryString;
			}
			set
			{
				this._queryString = value;
			}
		}
	}
}
