// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class MessageHeader
	{
		private int _protocol;
		private int _messageType;
		private long _correlationId;
		private long _messageId;
		private int _messageFlags;
		public int Protocol
		{
			get
			{
				return this._protocol;
			}
			set
			{
				this._protocol = value;
			}
		}
		public int MessageType
		{
			get
			{
				return this._messageType;
			}
			set
			{
				this._messageType = value;
			}
		}
		public long CorrelationId
		{
			get
			{
				return this._correlationId;
			}
			set
			{
				this._correlationId = value;
			}
		}
		public long MessageId
		{
			get
			{
				return this._messageId;
			}
			set
			{
				this._messageId = value;
			}
		}
		public int MessageFlags
		{
			get
			{
				return this._messageFlags;
			}
			set
			{
				this._messageFlags = value;
			}
		}
	}
}
