// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class SupportedProtocol
	{
		private int _protocol;
		private Energistics.Etp.v12.Datatypes.Version _protocolVersion;
		private string _role;
		private Dictionary<string,Energistics.Etp.v12.Datatypes.DataValue> _protocolCapabilities;
		public int Protocol
		{
			get
			{
				return this._protocol;
			}
			set
			{
				this._protocol = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Version ProtocolVersion
		{
			get
			{
				return this._protocolVersion;
			}
			set
			{
				this._protocolVersion = value;
			}
		}
		public string Role
		{
			get
			{
				return this._role;
			}
			set
			{
				this._role = value;
			}
		}
		public Dictionary<string,Energistics.Etp.v12.Datatypes.DataValue> ProtocolCapabilities
		{
			get
			{
				return this._protocolCapabilities;
			}
			set
			{
				this._protocolCapabilities = value;
			}
		}
	}
}
