// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class Version
	{
		private int _major;
		private int _minor;
		private int _revision;
		private int _patch;
		public int Major
		{
			get
			{
				return this._major;
			}
			set
			{
				this._major = value;
			}
		}
		public int Minor
		{
			get
			{
				return this._minor;
			}
			set
			{
				this._minor = value;
			}
		}
		public int Revision
		{
			get
			{
				return this._revision;
			}
			set
			{
				this._revision = value;
			}
		}
		public int Patch
		{
			get
			{
				return this._patch;
			}
			set
			{
				this._patch = value;
			}
		}
	}
}
