// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.DirectedDiscovery
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class GetResourcesResponse
	{
		private Energistics.Etp.v12.Datatypes.Object.GraphResource _resource;
		public Energistics.Etp.v12.Datatypes.Object.GraphResource Resource
		{
			get
			{
				return this._resource;
			}
			set
			{
				this._resource = value;
			}
		}
	}
}
