// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.DiscoveryQuery
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class FindResourcesResponse
	{
		private Energistics.Etp.v12.Datatypes.Object.Resource _resource;
		private string _serverSortOrder;
		public Energistics.Etp.v12.Datatypes.Object.Resource Resource
		{
			get
			{
				return this._resource;
			}
			set
			{
				this._resource = value;
			}
		}
		public string ServerSortOrder
		{
			get
			{
				return this._serverSortOrder;
			}
			set
			{
				this._serverSortOrder = value;
			}
		}
	}
}
