// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.WitsmlSoap
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class WMLS_GetBaseMsgResponse
	{
		private string _Result;
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				this._Result = value;
			}
		}
	}
}
