// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.WitsmlSoap
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class WMLS_DeleteFromStore
	{
		private string _WMLtypeIn;
		private string _XMLin;
		private string _OptionsIn;
		private string _CapabilitiesIn;
		public string WMLtypeIn
		{
			get
			{
				return this._WMLtypeIn;
			}
			set
			{
				this._WMLtypeIn = value;
			}
		}
		public string XMLin
		{
			get
			{
				return this._XMLin;
			}
			set
			{
				this._XMLin = value;
			}
		}
		public string OptionsIn
		{
			get
			{
				return this._OptionsIn;
			}
			set
			{
				this._OptionsIn = value;
			}
		}
		public string CapabilitiesIn
		{
			get
			{
				return this._CapabilitiesIn;
			}
			set
			{
				this._CapabilitiesIn = value;
			}
		}
	}
}
