// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.WitsmlSoap
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class WMLS_GetFromStoreResponse
	{
		private int _Result;
		private string _XMLout;
		private string _SuppMsgOut;
		public int Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				this._Result = value;
			}
		}
		public string XMLout
		{
			get
			{
				return this._XMLout;
			}
			set
			{
				this._XMLout = value;
			}
		}
		public string SuppMsgOut
		{
			get
			{
				return this._SuppMsgOut;
			}
			set
			{
				this._SuppMsgOut = value;
			}
		}
	}
}
