// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.GrowingObject
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class GetPartsMetadataResponse
	{
		private List<Energistics.Etp.v12.Datatypes.Object.PartsMetadataInfo> _metadata;
		private List<Energistics.Etp.v12.Datatypes.ErrorInfo> _errors;
		public List<Energistics.Etp.v12.Datatypes.Object.PartsMetadataInfo> Metadata
		{
			get
			{
				return this._metadata;
			}
			set
			{
				this._metadata = value;
			}
		}
		public List<Energistics.Etp.v12.Datatypes.ErrorInfo> Errors
		{
			get
			{
				return this._errors;
			}
			set
			{
				this._errors = value;
			}
		}
	}
}
