// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.Object
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class ObjectIndex
	{
		private Energistics.Etp.v12.Datatypes.IndexValue _indexValue;
		private string _uom;
		private string _depthDatum;
		public Energistics.Etp.v12.Datatypes.IndexValue IndexValue
		{
			get
			{
				return this._indexValue;
			}
			set
			{
				this._indexValue = value;
			}
		}
		public string Uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				this._uom = value;
			}
		}
		public string DepthDatum
		{
			get
			{
				return this._depthDatum;
			}
			set
			{
				this._depthDatum = value;
			}
		}
	}
}
