// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.Object
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class PartsMetadataInfo
	{
		private string _uri;
		private Energistics.Etp.v12.Datatypes.ChannelData.ChannelIndexKind _indexKind;
		private string _name;
		private Energistics.Etp.v12.Datatypes.Object.IndexInterval _indexInterval;
		private Dictionary<string,Energistics.Etp.v12.Datatypes.DataValue> _customData;
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.ChannelData.ChannelIndexKind IndexKind
		{
			get
			{
				return this._indexKind;
			}
			set
			{
				this._indexKind = value;
			}
		}
		public string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.IndexInterval IndexInterval
		{
			get
			{
				return this._indexInterval;
			}
			set
			{
				this._indexInterval = value;
			}
		}
		public Dictionary<string,Energistics.Etp.v12.Datatypes.DataValue> CustomData
		{
			get
			{
				return this._customData;
			}
			set
			{
				this._customData = value;
			}
		}
	}
}
