// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.Object
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class Resource
	{
		private string _uri;
		private string _contentType;
		private string _name;
		private Dictionary<string,System.String> _customData;
		private Energistics.Etp.v12.Datatypes.Object.ResourceKind _resourceType;
		private System.Nullable<int> _childCount;
		private System.Nullable<long> _lastChanged;
		private bool _objectNotifiable;
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public string ContentType
		{
			get
			{
				return this._contentType;
			}
			set
			{
				this._contentType = value;
			}
		}
		public string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public Dictionary<string,System.String> CustomData
		{
			get
			{
				return this._customData;
			}
			set
			{
				this._customData = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.ResourceKind ResourceType
		{
			get
			{
				return this._resourceType;
			}
			set
			{
				this._resourceType = value;
			}
		}
		[Microsoft.Hadoop.Avro.AvroUnion(typeof(Microsoft.Hadoop.Avro.AvroNull), typeof(int))]
		public System.Nullable<int> ChildCount
		{
			get
			{
				return this._childCount;
			}
			set
			{
				this._childCount = value;
			}
		}
		[Microsoft.Hadoop.Avro.AvroUnion(typeof(Microsoft.Hadoop.Avro.AvroNull), typeof(long))]
		public System.Nullable<long> LastChanged
		{
			get
			{
				return this._lastChanged;
			}
			set
			{
				this._lastChanged = value;
			}
		}
		public bool ObjectNotifiable
		{
			get
			{
				return this._objectNotifiable;
			}
			set
			{
				this._objectNotifiable = value;
			}
		}
	}
}
