// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.Object
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class SubscriptionInfo2
	{
		private Energistics.Etp.v12.Datatypes.Object.ContextInfo _context;
		private Energistics.Etp.v12.Datatypes.Uuid _requestUuid;
		private long _startTime;
		private bool _includeObjectData;
		public Energistics.Etp.v12.Datatypes.Object.ContextInfo Context
		{
			get
			{
				return this._context;
			}
			set
			{
				this._context = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Uuid RequestUuid
		{
			get
			{
				return this._requestUuid;
			}
			set
			{
				this._requestUuid = value;
			}
		}
		public long StartTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				this._startTime = value;
			}
		}
		public bool IncludeObjectData
		{
			get
			{
				return this._includeObjectData;
			}
			set
			{
				this._includeObjectData = value;
			}
		}
	}
}
