// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.ChannelDataLoad
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class OpenChannelResponse
	{
		private List<Energistics.Etp.v12.Datatypes.ChannelData.OpenChannelInfo> _channels;
		private List<Energistics.Etp.v12.Datatypes.ErrorInfo> _errors;
		public List<Energistics.Etp.v12.Datatypes.ChannelData.OpenChannelInfo> Channels
		{
			get
			{
				return this._channels;
			}
			set
			{
				this._channels = value;
			}
		}
		public List<Energistics.Etp.v12.Datatypes.ErrorInfo> Errors
		{
			get
			{
				return this._errors;
			}
			set
			{
				this._errors = value;
			}
		}
	}
}
