// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class ChannelSubscribeInfo
	{
		private long _channelId;
		private Energistics.Etp.v12.Datatypes.IndexValue _lastIndex;
		private bool _infill;
		private bool _dataChanges;
		public long ChannelId
		{
			get
			{
				return this._channelId;
			}
			set
			{
				this._channelId = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.IndexValue LastIndex
		{
			get
			{
				return this._lastIndex;
			}
			set
			{
				this._lastIndex = value;
			}
		}
		public bool Infill
		{
			get
			{
				return this._infill;
			}
			set
			{
				this._infill = value;
			}
		}
		public bool DataChanges
		{
			get
			{
				return this._dataChanges;
			}
			set
			{
				this._dataChanges = value;
			}
		}
	}
}
