// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class ChannelMetadataRecord
	{
		private string _uri;
		private long _id;
		private List<Energistics.Etp.v12.Datatypes.ChannelData.IndexMetadataRecord> _indexes;
		private string _channelName;
		private string _dataType;
		private string _uom;
		private string _measureClass;
		private Energistics.Etp.v12.Datatypes.ChannelData.ChannelStatusKind _status;
		private string _source;
		private List<System.Int32> _axisVectorLengths;
		private Dictionary<string,Energistics.Etp.v12.Datatypes.DataValue> _customData;
		private List<Energistics.Etp.v12.Datatypes.AttributeMetadataRecord> _attributeMetadata;
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public List<Energistics.Etp.v12.Datatypes.ChannelData.IndexMetadataRecord> Indexes
		{
			get
			{
				return this._indexes;
			}
			set
			{
				this._indexes = value;
			}
		}
		public string ChannelName
		{
			get
			{
				return this._channelName;
			}
			set
			{
				this._channelName = value;
			}
		}
		public string DataType
		{
			get
			{
				return this._dataType;
			}
			set
			{
				this._dataType = value;
			}
		}
		public string Uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				this._uom = value;
			}
		}
		public string MeasureClass
		{
			get
			{
				return this._measureClass;
			}
			set
			{
				this._measureClass = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.ChannelData.ChannelStatusKind Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public string Source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		public List<System.Int32> AxisVectorLengths
		{
			get
			{
				return this._axisVectorLengths;
			}
			set
			{
				this._axisVectorLengths = value;
			}
		}
		public Dictionary<string,Energistics.Etp.v12.Datatypes.DataValue> CustomData
		{
			get
			{
				return this._customData;
			}
			set
			{
				this._customData = value;
			}
		}
		public List<Energistics.Etp.v12.Datatypes.AttributeMetadataRecord> AttributeMetadata
		{
			get
			{
				return this._attributeMetadata;
			}
			set
			{
				this._attributeMetadata = value;
			}
		}
	}
}
