// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class DataItem
	{
		private long _channelId;
		private List<Energistics.Etp.v12.Datatypes.IndexValue> _indexes;
		private Energistics.Etp.v12.Datatypes.DataValue _value;
		private List<Energistics.Etp.v12.Datatypes.DataAttribute> _valueAttributes;
		public long ChannelId
		{
			get
			{
				return this._channelId;
			}
			set
			{
				this._channelId = value;
			}
		}
		public List<Energistics.Etp.v12.Datatypes.IndexValue> Indexes
		{
			get
			{
				return this._indexes;
			}
			set
			{
				this._indexes = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.DataValue Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		public List<Energistics.Etp.v12.Datatypes.DataAttribute> ValueAttributes
		{
			get
			{
				return this._valueAttributes;
			}
			set
			{
				this._valueAttributes = value;
			}
		}
	}
}
