// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class DataFrame
	{
		private List<System.Int64> _index;
		private List<Energistics.Etp.v12.Datatypes.DataValue> _data;
		public List<System.Int64> Index
		{
			get
			{
				return this._index;
			}
			set
			{
				this._index = value;
			}
		}
		public List<Energistics.Etp.v12.Datatypes.DataValue> Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
	}
}
