// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Datatypes.ChannelData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class IndexMetadataRecord
	{
		private Energistics.Etp.v12.Datatypes.ChannelData.ChannelIndexKind _indexKind;
		private Energistics.Etp.v12.Datatypes.Object.IndexInterval _interval;
		private Energistics.Etp.v12.Datatypes.ChannelData.IndexDirection _direction;
		private string _name;
		public Energistics.Etp.v12.Datatypes.ChannelData.ChannelIndexKind IndexKind
		{
			get
			{
				return this._indexKind;
			}
			set
			{
				this._indexKind = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.Object.IndexInterval Interval
		{
			get
			{
				return this._interval;
			}
			set
			{
				this._interval = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.ChannelData.IndexDirection Direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				this._direction = value;
			}
		}
		public string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
	}
}
