// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.Discovery
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class GetResources2
	{
		private Energistics.Etp.v12.Datatypes.Object.ContextInfo _context;
		public Energistics.Etp.v12.Datatypes.Object.ContextInfo Context
		{
			get
			{
				return this._context;
			}
			set
			{
				this._context = value;
			}
		}
	}
}
