// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.DataArray
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class DataArray
	{
		private List<System.Int64> _dimensions;
		private Energistics.Etp.v12.Datatypes.AnyArray _data;
		public List<System.Int64> Dimensions
		{
			get
			{
				return this._dimensions;
			}
			set
			{
				this._dimensions = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.AnyArray Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
	}
}
