// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.DataArray
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class PutDataArraySlice
	{
		private string _uri;
		private string _pathInResource;
		private Energistics.Etp.v12.Datatypes.AnyArray _data;
		private List<System.Int64> _dimensions;
		private List<System.Int64> _start;
		private List<System.Int64> _count;
		public string Uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public string PathInResource
		{
			get
			{
				return this._pathInResource;
			}
			set
			{
				this._pathInResource = value;
			}
		}
		public Energistics.Etp.v12.Datatypes.AnyArray Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		public List<System.Int64> Dimensions
		{
			get
			{
				return this._dimensions;
			}
			set
			{
				this._dimensions = value;
			}
		}
		public List<System.Int64> Start
		{
			get
			{
				return this._start;
			}
			set
			{
				this._start = value;
			}
		}
		public List<System.Int64> Count
		{
			get
			{
				return this._count;
			}
			set
			{
				this._count = value;
			}
		}
	}
}
