// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.StoreNotification
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class ObjectChanged
	{
		private Energistics.Etp.v12.Datatypes.Object.ObjectChange _change;
		public Energistics.Etp.v12.Datatypes.Object.ObjectChange Change
		{
			get
			{
				return this._change;
			}
			set
			{
				this._change = value;
			}
		}
	}
}
