// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.ChannelSubscribe
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class SubscribeChannels
	{
		private List<Energistics.Etp.v12.Datatypes.ChannelData.ChannelSubscribeInfo> _channels;
		public List<Energistics.Etp.v12.Datatypes.ChannelData.ChannelSubscribeInfo> Channels
		{
			get
			{
				return this._channels;
			}
			set
			{
				this._channels = value;
			}
		}
	}
}
