// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.Transaction
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class StartTransactionResponse
	{
		private Energistics.Etp.v12.Datatypes.Uuid _transactionUuid;
		public Energistics.Etp.v12.Datatypes.Uuid TransactionUuid
		{
			get
			{
				return this._transactionUuid;
			}
			set
			{
				this._transactionUuid = value;
			}
		}
	}
}
