// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Energistics.Etp.v12.Protocol.ChannelDataFrame
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	
	public class ChannelDataFrameSet
	{
		private List<System.Int64> _channels;
		private List<Energistics.Etp.v12.Datatypes.ChannelData.DataFrame> _data;
		public List<System.Int64> Channels
		{
			get
			{
				return this._channels;
			}
			set
			{
				this._channels = value;
			}
		}
		public List<Energistics.Etp.v12.Datatypes.ChannelData.DataFrame> Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
	}
}
